version: '3.8'

services:
  cloud-saas:
    image: cloud-saas:prod
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: cloud-saas-prod
    restart: always
    ports:
      # Expose port 8743 for the Cloudflare Tunnel daemon to route to
      - "127.0.0.1:8743:8000"
    environment:
      # Zero-Config Setup: Everything is pre-generated securely for this internal stack
      - DATABASE_URL=postgresql://booking:vps_secure_db_pass_123@db:5432/booking_saas
      - SECRET_KEY=04e4c31c3b9851ac61477753f65b9cec86139dadf43a3983f20133126fcff731
      - VAPID_PUBLIC_KEY=BCcDjJgojrN4JoU821flM4I5-b1_hTRRFouKmuc_TTvm4eKfNQbx--5wfEkTiORwN8DE5BgiGUIF1ZaBjDSy7P0
      # VAPID Private Key string
      - |
        VAPID_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----
        MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgN06qWGKWR0PhmsRS
        H9rvhL0IfKKiV7G9KnRPKwJdY2ehRANCAAQnA4yYKI6zeCaFPNtX5TOCOfm9f4U0
        URaLiprnP0075uHinzUG8fvucHxJE4jkcDfAxOQYIhlCBdWWgYw0suz9
        -----END PRIVATE KEY-----
    depends_on:
      - db
    networks:
      - saas-network

  db:
    image: postgres:15-alpine
    container_name: cloud-saas-db-prod
    restart: always
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: vps_secure_db_pass_123
      POSTGRES_DB: booking_saas
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - saas-network

volumes:
  postgres_data_prod:

networks:
  saas-network:
    driver: bridge
