from flask import Flask, request, jsonify, render_template_string

app = Flask(__name__)

# Seed 10 unique applicants
applicants = []
first_names = ["SHAHID", "AHMED", "ALI", "FATIMA", "AYESHA", "OMAR", "ZARA", "HASSAN", "SARA", "BILAL"]
surnames = ["RIAZ", "KHAN", "SYED", "TARIQ", "MALIK", "SHEIKH", "CHAUDHRY", "RANA", "IQBAL", "BAIG"]

for i in range(10):
    phone = f"31651859{i:02d}"
    applicants.append({
        "id": i + 1,
        "email": f"applicant{i+1}@example.com",
        "firstname": first_names[i],
        "surname": surnames[i],
        "dob": f"01/01/199{i}",
        "passport": f"FR32145{i}",
        "passport_exp": f"01/01/203{i}",
        "gender_id": "2" if i % 2 == 0 else "1",
        "nationality_id": "197",
        "phone_prefix_id": "197",
        "phone": phone,
        "type": "26",
        "bookingfor": "0",
        "status": "Pending",
        "booking_details": None
    })

# Simulate OTPs generated by the mobile app
otps = {a["phone"]: "123456" for a in applicants}

@app.route('/')
def index():
    html = """
    <html>
    <head><title>Internal Portal - Applicant Management</title></head>
    <body style="font-family: sans-serif; margin: 40px; background-color: #f4f4f9;">
        <div style="max-width: 1000px; margin: auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
            <h2 style="color: #333;">Internal Portal - Applicant Management</h2>
            <p style="color: #666;">This portal mimics your internal database API for fetching applicants and SMS OTPs.</p>
            
            <h3 style="border-bottom: 2px solid #eee; padding-bottom: 10px;">Current Applicants</h3>
            <table border="1" cellpadding="10" style="border-collapse: collapse; width: 100%; text-align: left;">
                <tr style="background: #0056b3; color: white;">
                    <th>ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Status</th><th>Booking Details</th>
                </tr>
                {% for a in applicants %}
                <tr style="background: {% if a.status == 'Confirmed' %}#d4edda{% else %}#fff3cd{% endif %};">
                    <td>{{ a.id }}</td>
                    <td>{{ a.firstname }} {{ a.surname }}</td>
                    <td>{{ a.email }}</td>
                    <td>{{ a.phone }}</td>
                    <td><strong>{{ a.status }}</strong></td>
                    <td>{% if a.booking_details %}{{ a.booking_details.date }} @ {{ a.booking_details.time }} (Slot ID: {{ a.booking_details.id }}){% else %}N/A{% endif %}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </body>
    </html>
    """
    return render_template_string(html, applicants=applicants)

@app.route('/add-applicant', methods=['POST'])
def add_applicant():
    # Kept for backward compatibility
    pass

@app.route('/get-applicants', methods=['GET'])
def get_applicants():
    # Only return Pending applicants so bots pick up unbooked ones
    pending = [a for a in applicants if a["status"] == "Pending"]
    return jsonify(pending)

@app.route('/update-status', methods=['POST'])
def update_status():
    data = request.json
    applicant_id = data.get("id")
    for a in applicants:
        if a["id"] == applicant_id:
            a["status"] = "Confirmed"
            a["booking_details"] = data.get("slot")
            return jsonify({"success": True}), 200
    return jsonify({"error": "Not found"}), 404

@app.route('/get-otp', methods=['GET'])
def get_otp():
    phone = request.args.get('phone')
    if phone in otps:
        return jsonify({"otp": otps[phone]})
    return jsonify({"error": "No OTP found for this phone number"}), 404

if __name__ == '__main__':
    app.run(port=5001, debug=True)

